### ISSUE TITLE
model

### ISSUE THREAD

**Issue by yzc111** [xiangtanshi/CounterAL#2]
Hello, where is model dir?

**Comment by xiangtanshi** [comment]
I think you are asking about the problem in the instructions in Readme, and thanks for pointing out this typo. The command should be "cd utils\n python model.py" instead of "cd model\n python model.py", and the model dir will be made by this file.  I have revised it in the main branch, I hope this reply solves your problem.

**Comment by yzc111** [comment]
thanks~
